### ISSUE TITLE
Broken seteuid() call in official OOS13 due to missing kernel commits

### ISSUE THREAD

**Issue by aviraxp** [OnePlusOSS/android_kernel_oneplus_sm8350#18]
When debugging system, I found that seteuid() call is completely broken. After some search, I found that it is kernel issue. This issue influences official ColorOS and OOS 13 with sm8250/sm8350.

Take sm8350_t_13.0.0_op9rt branch as an example. In the big commit [Synchronize codes for OnePlus 9RT 5G MT2110_11_F.07/MT2111_11_F.07](https://github.com/OnePlusOSS/android_kernel_oneplus_sm8350/commit/85301e3711e9d594d63fc1fd71ac0f28df15c816), upstream patch "[binder: use euid from cred instead of using task](https://android.googlesource.com/kernel/common/+/28a1e470b000d45bcf6c05f18a01d07cdc0b3235)" is picked, but the subsequent fix commit "[binder: fix test regression due to sender_euidchange](https://android.googlesource.com/kernel/common/+/aaa83768ba39586fe0abe2fb1825b89f3bf6270c)" is not. This causes caused some Android system test regressions, as described in the fix commit itself. This makes CTS like CredentialsTest#CaptureLayersTest test fail, and will cause more problems for end users. Same issue exists in SM8250 kernel too.

Solution is simple: pick  "[binder: fix test regression due to sender_euidchange](https://android.googlesource.com/kernel/common/+/aaa83768ba39586fe0abe2fb1825b89f3bf6270c)" .

**Comment by aviraxp** [comment]
@OnePlusOSSAdmin Please deliver the issue to kernel developers. They know what I mean. Thx!

**Comment by OnePlusOSSAdmin** [comment]
Thanks for your feedback. We’ll synchronize code with the latest version and this fix would be patched.
________________________________
一加  OnePlus

本电子邮件及其附件含有一加公司的保密信息，仅限于邮件指明的收件人（包含个人及群组）使用。禁止任何人在未经授权的情况下以任何形式使用。如果您错收了本邮件，切勿传播、分发、复制、印刷或使用本邮件之任何部分或其所载之任何内容，并请立即以电子邮件通知发件人并删除本邮件及其附件。
网络通信可能含有计算机病毒或其它缺陷，可能无法准确和/或及时送达其它系统，亦可能受阻而不为发件人或指定收件人所知。一加对此类错误或遗漏以及任何因使用本邮件而引致之任何损失概不承担责任。一加谨保留与本邮件相关之一切权利。
除非明确说明，本邮件及其附件无意作为在任何国家或地区之要约、招揽或承诺，亦无意作为任何交易或合同之正式确认。 发件人、其所属机构或所属机构之关联机构或任何上述机构之股东、董事、高级管理人员、员工或其他任何人（以下称“发件人”或“一加”）不因本邮件之误送而放弃其所享之任何权利，亦不对因故意或过失使用该等信息而引发或可能引发的损失承担任何责任。
文化差异披露：因全球文化差异影响，单纯以YES\OK或其他简单词汇的回复并不构成发件人对任何交易或合同之正式确认或接受，请与发件人再次确认以获得明确书面意见。发件人不对任何受文化差异影响而导致故意或错误使用该等信息所造成的任何直接或间接损害承担责任。
This e-mail and its attachments contain confidential information from OnePlus , which is intended only for the person or entity whose address is listed above. Any use of the information contained herein in any way (including, but not limited to, total or partial disclosure, reproduction, or dissemination) by persons other than the intended recipient(s) is prohibited. If you are not the intended recipient, please do not read, copy, distribute, or use this information. If you have received this transmission in error, please notify the sender immediately by reply e-mail and then delete this message.
Electronic communications may contain computer viruses or other defects, may not be accurately and/or timely transmitted to other systems, or may be intercepted, delayed, deleted or interfered with without the knowledge of the sender or the intended recipient(s). OnePlus makes no warranties in relation to these matters. Please note that OnePlus reserves all rights in connection with the email.
Unless expressly stated, this e-mail and its attachments are provided without any warranty, acceptance or promise of any kind in any country or region, nor constitute a formal confirmation or acceptance of any transaction or contract. The sender, together with its affiliates or any shareholder, director, officer, employee or any other person of any such institution (hereinafter referred to as "sender" or " OnePlus ") does not waive any rights and shall not be liable for any damages that arise or may arise from the intentional or negligent use of such information.
Cultural Differences Disclosure: Due to global cultural differences, any reply with only YES\OK or other simple words does not constitute any confirmation or acceptance of any transaction or contract, please confirm with the sender again to ensure clear opinion in written form. The sender shall not be responsible for any direct or indirect damages resulting from the intentional or misuse of such information.

**Comment by ppajda** [comment]
@OnePlusOSSAdmin I hope SM8250 will gets this too, btw will there be kernel source drop for 8/t/pro or will are stick to op9r branch?

**Comment by aviraxp** [comment]
The issue is still not fixed in sm8250.
